export const APP_NAME = "ICONIC 2024";

export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  OUR_TEAM: "/about/our-team",
  REVIEWERS: "/reviewers",
  JOIN_THE_MOVEMENT: "/join-the-movement",
  SUBJECT: "/program-and-subject-overview/subject",
  EVENTS: "/program-and-subject-overview/events",
  DAY_ONE: "/program-and-subject-overview/events/day-1",
  DAY_TWO: "/program-and-subject-overview/events/day-2",
  DAY_THREE: "/program-and-subject-overview/events/day-3",
  SPEAKERS: "/program-and-subject-overview/speakers",
  PARTNERSHIP: "/partnership",
  DURING_THE_STAY: "/during-the-stay",
  PREPARATION: "/during-the-stay/preparation",
  VENUE: "/during-the-stay/venue",
  ONLINE_PARTICIPANT: "/during-the-stay/online-participant",
  CITY_DAY_TRIP: "/during-the-stay/city-day-trip",
  FAQ: "/during-the-stay/faq",
  EVENT_REGISTRATION: "/event-registration",
  SUBMISSION: "/submission",
  SUBMISSION_GUIDELINES: "/submission/submission-guideline",
};

export const BREADCRUMB_LABELS = {
  [PATHS.HOME]: "Home",
  [PATHS.ABOUT]: "About",
  [PATHS.OUR_TEAM]: "Our Team",
  [PATHS.REVIEWERS]: "Reviewers",
  [PATHS.SUBJECT]: "Subject Overview",
  [PATHS.EVENTS]: "Events Overview",
  [PATHS.DAY_ONE]: "Day 1",
  [PATHS.DAY_TWO]: "Day 2",
  [PATHS.DAY_THREE]: "Day 3",
  [PATHS.SPEAKERS]: "Speakers",
  [PATHS.PARTNERSHIP]: "Partnership",
  [PATHS.DURING_THE_STAY]: "During the Stay",
  [PATHS.PREPARATION]: "Preparation",
  [PATHS.VENUE]: "Venue",
  [PATHS.ONLINE_PARTICIPANT]: "Online Participant",
  [PATHS.CITY_DAY_TRIP]: "City Day Trip",
  [PATHS.FAQ]: "FAQ",
  [PATHS.EVENT_REGISTRATION]: "Event Registration",
  [PATHS.SUBMISSION]: "Submission",
  [PATHS.SUBMISSION_GUIDELINES]: "Submission Guidelines",
};
